# make it explicit that we favor the new container-based travis workers
# https://travis-ci.com/arita37/a_aapackage
sudo: false

language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: xenial

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/sklearn
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4
    - DISTRIB="ubuntu" PYTHON_VERSION="3.5"
    - NUMPY_VERSION="1.11.0"
    - SCIPY_VERSION="0.17.0"
    - PILLOW_VERSION="4.0.0"
    - JOBLIB_VERSION="0.11"
    - COVERAGE=true
    - SKLEARN_SITE_JOBLIB=1

addons:
  apt:
    packages:
      # these only required by the DISTRIB="ubuntu" builds:
      - python3-scipy
      - libatlas3-base
      - libatlas-base-dev
      - libatlas-dev

install: source zbuild/travis/install.sh
script: 
  # - bash zbuild/travis/test_script.sh
  # - bash zbuild/travis/test_docs.sh
  # - bash zbuild/travis/test_pytest_soft_dependency.sh
  - python ztest_import.py
